---
title: "Onion price hike in Bangladesh"
output:
 pagedown::html_paged:
  css: ["./tpaged-page.css"]
---

# Introduction

## Background 

While  browsing for news on onion prices in Bangladesh, an interesting piece of report came to my notice. It was a news published on the Daily Star, December 02, 2019 about the Jatiya Sangshad proceedings. Tofail Ahmed, then chairman of parliament standing committee on commerce said there was no syndicate in the onion market and the prices of the bulb could not be brought down by force.

By far, this was the most sensible comment I have ever heard from an influential political personality  and a Minister holding important portfolio.

## Basic economics

In any moderately decent economics 101 course taught in any university around the world, one of the fundamental topics that an instructor teach is how market works, particularly   a competitive market.  Onion has the all the hallmark of a textbook case of nearly perfectly competitive market. It has the attribute of  being an identical product across the board, the market has many buyers and sellers. Every sellers can freely enter the market and also exit. As a result, onion sellers have little power in influencing prices, let alone set prices.

## The market problem

Therefore, I feel irritated, to put it mildly,  whenever I see the topic of syndicate comes up in the discussion of onion price or in general in the case of daily essentials. Sadly, the standard belief among policy makers and general populace is that unscrupulous businessman takes advantage of a crisis situation and rips high benefits from spiralling price. But in a competitive market it is nearly impossible. In  onion market of Bangladesh, sellers or businessmen as individuals or a group find it very difficult to control the market if not nearly impossible. 

# India factor

## Production and import

Let's take the case of recent situation in onion market. The current increase in onion price is not surprising at all. It has played out in the similar fashion many times in the recent history of Bangladesh. According to Directorate of Agricultural Marketing (DAM), there is a demand of around 3 million metric tons of onion in 2020. How this demand is calculated is not clear and why this is a major problem is another issue. We will touch upon on it a little bit later. On the other hand, in 2020, total production of onion in Bangladesh was around 2.6 million metric ton. Since it is a perishable product, around 25-30% gets wasted or rotten. After deducting that part, net production results in 18 to 19 lakh metric ton. The rest 11 lakh metric ton of onions are imported. Therefore, for more than one-third of the total demand has to be imported and bulk of this import comes from India.

## Domestic market in India

India is producer of more than one-fifth of total onion production in the world. Out of this production, more than 50 percent is produced in three states of India: Maharashtra, Karnataka and Gujrat. Whenever some adverse weather condition occurs in these states, may be in the form of heavy rain or drought, production of onion is affected. As a result, supply in the market is disrupted and price of onion starts to go up in Indian market. To prevent prices go spiraling up, Indian government tries to ensure maximum supply available in the local market. In that regard,  they either set high minimum exports price or bans  exports of onion. 

## Indian Politics

In the recent past, Indian government showed remarkable consistency and alacrity in  taking quick action against onion price hike. This is no surprise since  onion price is a very sensitive issue in India's politics. Few elections have been won and lost on high onion prices. The most famous of this phenomenon was India's parliamentary election of 1980, also known as 'onion election'. Indira Gandhi was the main contender from Congress(I) contesting against caretaker government's head, Charan Singh and  his party `Lok Dal`. Indira Gandhi was trying to bounce back from her ignominious defeat back in 1977 when she was ousted after two year emergency period. Before the 1980 election, in election campaign speeches, Indira Gandhi used to wear onion garlands before appearing into those campaigns. Her election rhetoric mostly pointed at the utter failure of incumbent government in controlling spiraling onion price. 

It worked. 

Indira Ghandhi's Congress(I) achieved a landslide victory in that election. Among 520 seats, her party won close to 400 seats where Lak Dal won only 39 seats. This is one of the biggest win for Congress in its entire history, only comparable to Jawharlal Nehru's win in 1952 in the backdrop as hero of the independence from colonial rule of British Raj.

This is not the only onion influenced political event in India's history. Another such situation occured in state elections of Delhi and Rajasthan in 1998. BJP for the first time in their history  came into the power. On top of that, Atal Bihari Bajpayee, the then prime minister, was riding high after successfully completing nuclear tests and achieving a moral political victory against arch rival Pakistan. But these remarkable feat was no match for a lowly onion when its price started to go up. BJP lost heavily in those state elections. A planning commission member of India once commented: for a substantial part of the population of India, onion price is the main indicator of inflation. A person's well-being  is gauged often by his/her ability to buy onion. 

Therefore, it is  no wonder that India reacts heavily to any hint in the price of onion. But it is  not that India's policy of controlling export is without any criticism. Particularly, this policy is highly unpopular among the farmers since it hampers the natural rise in prices.

Anyway, that is an issue of  India's internal market management system. In the case of Bangladesh, the onion price is not such highly politically sensitive issue but its an important daily product no doubt.  But the way concerned authority in Bangladesh reacts to India's onion policy  is quite disappointing.

# Bangladesh reaction 

Whenever India imposes some sort of restrictions regarding onion, minister or high flying political leaders at the beginning shows some form of discontent. When market situation gets worse in terms of onion price, their degree of displeasure at India's policy rises. After a while, when  they get over with their emotional distress with India, they typically resort to measures that they know as the  easiest in terms of public relations. They start to deploy RAB, police, mobile court magistrates to punish any seller who they think are selling onion higher than the "acceptable" price.

# Punishing traders

This is the most amusing part. Who decides which price is  acceptable or appropriate  in any given market at any given point time of the market? It's the market itself. It has  never been possible to tame a market by force, it never happened before and will never happen in the future.

It is  mind boggling that people in the highest possible decision making do not understand this simple economics. The remark by Minister Tofail Ahmed I mentioned in the beginning was just an exception and not representative of  how it works in the reality. After that remark in last December, this year same thing happened in the market.   According to a report in Dhaka Tribune Sep 17, 2020, three onion traders were fined Tk 2000 in Dinajpur. In Benapole, three more onion traders were penalized Tk 30000. In Lakhipur, a mobile court fined two wholesalers Tk 6000 for selling onions.

When authority goes after business, initially it seems that tactic worked, price goes down a bit. But after a while, the price situation gets even worse. Many sellers reduce market activities, some even close down entirely. As a result, price shoots up even higher then it would normally have. In this stage, when authority finds that price of onion is not coming down after their heavy handed approach on sellers, they announce they are looking for imports from new destinations. But that announcement comes a little too late. Price only starts to come down after new crop is harvested  into November or after India  withdraws its export ban.

# Same cycle repeated

In the mean time, onion consumers suffer greatly. In Bangladesh, the well-offs, elites can do away with a high price of onion but many poverty stricken people can not. Particularly, those with small businesses such as  restaurants, road-side food carts, high onion price imposes substantial financial burden. 

Year after year, this same cycle has been repeated in Bangladesh. Policy makers need to understand that we experience steep rise in price whenever there is   imbalance in the supply and demand. If supply exceeds demand, price starts to fall and vice versa. There is hardly any scope for manipulation in a competitive market. 

Therefore, its high time the policy makers starts to look into this crucial aspect of the market. Efforts need to be made  to have proper estimates of supply and demand. Difficult part is the demand side. It requires digging deeper into the food habits of individual. Only systematic and serious research efforts can figure that out. 

Compared to estimating demand, estimating supply is relatively easy. It is  all about how efficiently government's  agricultural extension wing is working. A properly functioning extension service should have regular estiamtes of the amount of land devoted to onion each year. From this information, it is not difficult to calculate total onion production. 

If the government keeps a close eye on the supply and demand situation, it can easily develop an early warning system. This system will provide an heads up regarding production shortfall and corresponding price hike. We need to remember that private sector already has come up with their own mechanism.  Even before the India's export ban came into effect on Sep 14, private traders started to take initiative to import onions from other sources than India. They began the process of taking import permission from Sep 3. According Chittagong Plant Quarantine Station (Sea port), 24 enterprises have so far taken permission for import around 10 thousand metric tons of onions from China, Myanmar, Pakistan, Egypt and Turkey (Dhaka Tribune, Sep 15). If businessman can acquire advanced information regarding onion market, the government should be able to do it even better.

There is another problem regarding statistical accuracy of demand and supply information. Let me cite a very recent example of mismatch between the numbers cited by government sources. In 2017, total demand for onion in Bangladesh was estimated to be 22-24 lakh metric ton. In the same year, around 19 lakh metric ton of onions have been produced. Total import has been around 10 lakh metric ton. Therefore, total availability of onion in the market is higher by 6 lakh metric ton, 25% higher than the demand. Even if we deduct the usual wastage of 25% of total production, the net production in that year was around 15 lakh metric ton. With another 10 lakh of metric ton on imports, the total supply seems to be  at par with the demand. Then why the price surpassed 100 tk in the year, more than three fold then the normal price?

One possible explanation is that the demand estimate might be flawed. The reason is that in government documents its hard to find a systematic and reliable approach to calculate demand. But even we consider all the estimates are correct still it can cause a price spiral. It all depends on the dynamics and timing of production and import. For example, if import orders comes through  after a steep and sustainable rise in  the price, then the damage is already done. But at the end of the year, statistics will show sufficient market supply. Stock and flow concepts come into the play. The stock measure may not detect any discrepancy but flow of production, availability, import timing all are highly crucial for pricing of daily essentials.

# Conclusion

Having considered all the above factors, we find that after all these years no systematic approach has been devised by the concerned authority in Bangladesh to deal with a supply shock in onion market. But the steep rise in price of onion need not happen in Bangladesh. With appropriate measures and foresightedness, this can be easily prevented. Its high time we move towards that direction.



